# Generated by Django 3.1.7 on 2021-04-04 14:00

from django.db import migrations, models
import enroll.fields


class Migration(migrations.Migration):
    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.PositiveSmallIntegerField(
                choices=[(1, 'new_user'), (2, 'student'), (3, 'teacher'), (4, 'moderator')],
                default=1),
        ),
        migrations.AlterField(
            model_name='offer',
            name='exchange_to',
            field=models.ManyToManyField(blank=True, to='enroll.ClassTime'),
        ),
        migrations.AlterField(
            model_name='classtime',
            name='day',
            field=enroll.fields.DayOfTheWeekField(
                choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'),
                         ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'),
                         ('SUNDAY', 'Sunday')], max_length=10),
        ),
    ]
