# Generated by Django 3.2 on 2021-05-13 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0002_auto_20210404_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=280)),
                ('active', models.BooleanField(default=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.enrollment')),
                ('exchange_to', models.ManyToManyField(blank=True, to='enroll.ClassTime')),
                ('lecturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enroll.lecturer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
